### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by akorchyn**
@race-of-sloths-stage

### CODE REVIEW

**Comment by race-of-sloths-stage** [comment]
@akorchyn Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths-website.vercel.app)!
You are true leader! Other sloths hot on your heels, keep moving!

sloth_stats



<details><summary>Current status: <i>waiting for finalization</i></summary>

The pull request is merged, you have 24 hours to finalize your scoring. The scoring ends Wed Jul  3 13:27:12 2024
| Reviewer | Score |
|--------|--------|
| @yurturdev  | 13 |

**The average score is 13**

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths-stage inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths-website.vercel.app/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths-website.vercel.app/profile/akorchyn)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths-website.vercel.app) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths-stage include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths-stage score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths-stage exclude` to send this PR back to the drawing board.
  - **Pause Race:** `@race-of-sloths-stage pause` to stop me on your repo.

</details>

**Comment by yurturdev** [comment]
@race-of-sloths-stage score 13

**Comment by race-of-sloths-stage** [comment]
### 🌟 Score recorded!

@yurturdev, thank you for scoring this pull request in the Race of Sloths!

**Comment by race-of-sloths-stage** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 13!
You have received 143 (130 base + 10% lifetime bonus) Sloth points for this contribution


We would appreciate your feedback or contribution idea that you can submit [here](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose

**Pull request merged**
