### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by yurturdev**
@race-of-sloths-stage

### CODE REVIEW

**Comment by race-of-sloths-stage** [comment]
@yurturdev Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths-website.vercel.app)!
Do you want to apply for monthly streak? Get 8+ score for a single PR this month and receive boost for race-of-sloth

sloth_stats



<details><summary>Current status: <i>executed</i></summary>

| Reviewer | Score |
|--------|--------|
| @akorchyn  | 8 |

**The average score is 8**

@yurturdev check out your results on the [Race of Sloths Leaderboard!](https://race-of-sloths-website.vercel.app/leaderboard) and in the [profile](https://race-of-sloths-website.vercel.app/profile/yurturdev)

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths-stage inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths-website.vercel.app/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths-website.vercel.app/profile/yurturdev)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths-website.vercel.app) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths-stage include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths-stage score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths-stage exclude` to send this PR back to the drawing board.
  - **Pause Race:** `@race-of-sloths-stage pause` to stop me on your repo.

</details>

**Comment by akorchyn** [comment]
@race-of-sloths-stage score 8

**Comment by race-of-sloths-stage** [comment]
### 🌟 Score recorded!

@akorchyn, thank you for scoring this pull request in the Race of Sloths!

**Comment by race-of-sloths-stage** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 8!
You have received 100 (80 base + 20 monthly bonus) Sloth points for this contribution


Congratulations @yurturdev! Your PR was highly scored and you completed another monthly streak! To keep your monthly streak make another pull request next month and get 8+ score for it

**Pull request merged**
