### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by akorchyn**
@race-of-sloths-stage

### CODE REVIEW

**Comment by race-of-sloths-stage** [comment]
@akorchyn Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths-website.vercel.app)!
Great job! Usain Bolt jealous of your results!

<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.staging.race-of-sloths.com/akorchyn?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.staging.race-of-sloths.com/akorchyn?type=bot&theme=light">
    Shows an illustrated sun in light mode and a moon with stars in dark mode.
</picture>




<details><summary>Current status: <i>executed</i></summary>

| Reviewer | Score |
|--------|--------|
| @yurturdev  | 8 |

**The average score is 8**

@akorchyn check out your results on the [Race of Sloths Leaderboard!](https://race-of-sloths-website.vercel.app/leaderboard) and in the [profile](https://race-of-sloths-website.vercel.app/profile/akorchyn)

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths-stage inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths-website.vercel.app/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths-website.vercel.app/profile/akorchyn)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths-website.vercel.app) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths-stage include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths-stage score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths-stage exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths-stage pause` to stop bot activity in this repo until `@race-of-sloths-stage unpause` command is called

</details>

**Comment by yurturdev** [comment]
@race-of-sloths-stage 6

**Comment by race-of-sloths** [comment]
@race-of-sloths-stage 8

**Comment by yurturdev** [comment]
@race-of-sloths-stage 8

**Comment by race-of-sloths-stage** [comment]
### 🌟 Score recorded!

@yurturdev, thank you for scoring this pull request in the Race of Sloths!

**Comment by akorchyn** [comment]
[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.staging.race-of-sloths.com/akorchyn?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.staging.race-of-sloths.com/akorchyn?type=bot&theme=light">
 Shows an illustrated sun in light mode and a moon with stars in dark mode.
</picture>](https://race-of-sloths.com/profile/akorchyn)

**Comment by akorchyn** [comment]
@race-of-sloths-stage score 5

**Comment by race-of-sloths-stage** [comment]
### ❌ Self-scoring is not permitted. 
Let's keep it fair! 👍

**Comment by akorchyn** [comment]
Finally!

image

@akorchyn Thank you for pushing it!

I am awarding it 13 points to account for the whole effort!

I am awarding it 13 points to account for the whole effort that started from nearcore and throughout all the dependencies!

@race-of-sloths-stage score 13

**Comment by race-of-sloths-stage** [comment]
### ❌ Self-scoring is not permitted. 
Let's keep it fair! 👍

**Comment by race-of-sloths-stage** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 8!
You have received 88 (80 base + 10% lifetime bonus) Sloth points for this contribution

**Pull request merged**
